.TH poca 1
.SH NAME
poca \- A fast and highly customizable command line podcast client
.SH SYNOPSIS
\fBpoca [-h] [-c CONFIG_DIR] [-q] [-l] [-e] [-t THREADS]
\f1
.SH DESCRIPTION
\fIPoca\f1 is a command line podcast aggregator with a focus on user control. It allows the user to manage and customize their subscriptions, setting limits on the number of files, filtering feeds, automatically adjusting metadata and more.
.SH OPTIONS
.TP
\fB-h\f1, \fB--help\f1
Show help message and exit.
.TP
\fB-c\f1, \fB--config\f1 \fICONFIG_DIR\f1
Use alternative configuration directory. Default is ~/.poca.
.TP
\fB-q\f1, \fB--quiet\f1
Run in quiet mode. This turns off all printing to standard output which is useful when running the program as a cron job. Quiet mode does not conflict with using the logging option.
.TP
\fB-l\f1, \fB--logfile\f1
Enable logging to the file 'poca.log' in the ~/.poca directory.
.TP
\fB-e\f1, \fB--email\f1
Enable email logging. Requires valid email configuration in poca.xml.
.TP
\fB-t\f1, \fB--threads\f1
Number of concurrent downloads to allow.
.SH FILES
\fI$HOME/.poca\f1 is the default user-specific configuration directory for \fIPoca\f1.

\fIpoca.xml\f1 is poca's configuration file. It is written in a custom XML format, designed to be fairly intuitive. It has three main components:

The 'settings' section has options such as where to download the audio files and optional id3 tagging and email account options.

The 'defaults' section contains subscription settings, like the maxmimum number of files to download, and apply them globally.

The 'subscriptions' section contains all the subscriptions in individual 'subscription' nodes.

\fI$CONFIG_DIR/db/*\f1 is the program's memory. These files - one for each subscription - keep track of what files are currently held.

\fI$CONFIG_DIR/poca.log\f1 is the log file (plaintext). The program writes all output to this file, if the -l switch is used.

.SH DOCUMENTATION
For in-depth information please go to \fBhttps://poca.readthedocs.io/en/latest/\f1.

.SH AUTHOR
\fIPoca\f1 was written by Mads Mide Michelsen <mail@brokkr.net>. For more information on the code go to \fBhttps://github.com/brokkr/poca\f1
.SH COPYRIGHT
Copyright 2010-2021 Mads Mide Michelsen

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see \fBhttp://www.gnu.org/licenses/\f1
.SH BUGS
The author is grateful for any notification of bugs and/or requests. Please go to \fBhttps://github.com/brokkr/poca/issues\f1 to report.
