#!/usr/bin/env python3

#  Copyright 2010-2017 Mads Michelsen (mail@brokkr.net)
# This file is part of Poca.
# Poca is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.

"""A cron-friendly command line podcast aggregator"""


import sys
import copy
import pathlib

from queue import Queue
from time import sleep

import poca


def main():
    '''Main script'''
    try:

        # args to paths
        args = poca.args.get_poca_args()
        stream_logger = poca.loggers.start_stream_logger(args)
        streamfail_logger = poca.loggers.start_after_stream_logger(args)
        paths = poca.config.Pocapaths(args)
        summary_logger = poca.loggers.start_summary_logger(args, paths)
        # poca
        poca_yaml = poca.config.read_yaml(paths.config_file)
        state_yaml = poca.config.get_state(paths.state_file)
        subs = poca_yaml.pop('subscriptions')
        defaults = poca_yaml.pop('defaults')
        # base_dir isn't checked as part of paths (base_dir not existing ->
        # fail)
        base_dir = pathlib.Path(poca_yaml['settings'].pop('base_dir'))
        dl_settings, id3_settings = poca.config.get_settings(poca_yaml)

        # state
        #state_yaml = config.read_yaml(paths.state_file)
        # start identifying log_file and get state.yaml -> blocklist etc.

        #print('paths')
        #print(paths.config_dir, paths.config_file, paths.state_file, paths.log_file)
        #print('subs')
        #print(subs)
        #print('defaults')
        #print(defaults)
        #print('base_dir')
        #print(base_dir)
        #print('dl_settings')
        #print(dl_settings)
        #print('id3_settings')
        #print(id3_settings)

        #sys.exit()

        # update loop
        update_threads = []
        update_q = Queue()
        skip_subs = []
        state_tmpl = {'etag': None, 'modified': None, 'current': {},
                      'blocked': [], 'active': True, 'image': 0}
        for sub in subs:
            state = state_yaml.pop(sub['title']) if sub['title'] in \
                state_yaml else copy.deepcopy(state_tmpl)
            #print(state)
            # if args.force -> reset etag and modified in state
            update_thread = poca.subupdate.SubUpdateThread(update_q,
                poca.subupdate.SubUpdate, sub, defaults, state, base_dir)
            update_threads.append(update_thread)
            update_thread.start()

        # upgrade loop
        state_q = Queue()
        upgrade_threads = []
        max_threads = args.threads if not args.verbose else 1
        while len(upgrade_threads) + len(skip_subs) < len(subs):
            state_infos = list()
            while not state_q.empty():
                state_infos.append(state_q.get())
            if state_infos:
                _update = poca.state.Update(paths.state_file, state_infos)
            while (len([t for t in upgrade_threads if t.is_alive()])
                   <= max_threads and not update_q.empty()):
                subdata = update_q.get()
                if subdata.outcome.success is False:
                    poca.output.plans_error(subdata)
                    skip_subs.append(subdata)
                    update_q.task_done()
                    continue
                if subdata.feedstatus.http_code == 301:
                    outcome = poca.subscribe.update_url(args, subdata)
                    poca.output.plans_moved(subdata, outcome)
                if subdata.feedstatus.http_code == 304:
                    skip_subs.append(subdata)
                    update_q.task_done()
                    poca.output.plans_nochanges(subdata)
                    continue
                poca.output.plans_upgrade(subdata)
                upgrade_thread = poca.subupgrade.SubUpgradeThread(update_q,
                    poca.subupgrade.SubUpgrade, state_q, subdata, dl_settings,
                    id3_settings)
                upgrade_threads.append(upgrade_thread)
                upgrade_thread.start()
            sleep(0.5)

        for upgrade_thread in upgrade_threads:
            upgrade_thread.join()

        state_infos = list()
        while not state_q.empty():
            state_infos.append(state_q.get())
        if state_infos:
            _update = poca.state.Update(paths.state_file, state_infos)
        #print(state_q.qsize())

        # wrap up
        poca.output.after_stream_flush()
        poca.output.email_summary()

    except KeyboardInterrupt:
        for thread in upgrade_threads:
            setattr(thread, "kill", True)
        sys.exit()


if __name__ == '__main__':
    main()
