#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright 2010-2017 Mads Michelsen (mail@brokkr.net)
# This file is part of Poca.
# Poca is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.

"""A subscription management tool for poca"""


import poco


def main():
    '''Main script'''
    args = poco.args.get_poca_subscribe_args()
    args.quiet = False
    stream_logger = poco.loggers.start_streamlogger(args)
    config = poco.config.Config(args)
    if args.cmd_name == 'delete':
        poco.subscribe.delete(config, args)
    elif args.cmd_name == 'add':
        sub_dic, sub_category = poco.subscribe.user_input_add_sub()
        poco.subscribe.add_sub(config, sub_category, sub_dic)
    elif args.cmd_name == 'list':
        poco.subscribe.list_subs(config)
    elif args.cmd_name == 'state':
        poco.subscribe.set_state(config)
    elif args.cmd_name == 'search':
        pass

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
