#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#  Copyright 2010-2017 Mads Michelsen (mail@brokkr.net)
# This file is part of Poca.
# Poca is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.

"""A cron-friendly command line podcast aggregator"""


import sys
from queue import Queue
from time import sleep

import poco


def main():
    '''Main script'''
    try:

        # setup
        args = poco.args.get_poca_args()
        stream_logger = poco.loggers.start_stream_logger(args)
        streamfail_logger = poco.loggers.start_after_stream_logger(args)
        conf = poco.config.Config(args, merge_default=True)
        summary_logger = poco.loggers.start_summary_logger(args, conf.paths,
                                                          conf.xml.settings)
        update_threads = []
        update_q = Queue()
        upgrade_threads = []
        skip_subs = []

        # update loop
        xp_str = './subscription[not(@state="inactive")][title][url]'
        valid_subs = conf.xml.subscriptions.xpath(xp_str)
        sub_names = [sub.title.text for sub in valid_subs]
        dupes = set([x for x in sub_names if sub_names.count(x) > 1])
        if len(dupes) > 0:
            msg = "Found the following duplicate titles: %s" % ', '.join(dupes)
            poco.output.config_fatal(msg)
        for sub in valid_subs:
            update_thread = poco.subupdate.SubUpdateThread(
                update_q, poco.subupdate.SubUpdate, conf, sub)
            update_threads.append(update_thread)
            update_thread.start()
        for update_thread in update_threads:
            update_thread.join()

        # upgrade loop
        while len(upgrade_threads) + len(skip_subs) < len(valid_subs):
            while (len([t for t in upgrade_threads if t.is_alive()])
                   < args.threads and not update_q.empty()):
                subdata = update_q.get()
                #print(subdata.sub.title.text, subdata.status)
                if subdata.outcome.success is False:
                    poco.output.plans_error(subdata)
                    skip_subs.append(subdata)
                    update_q.task_done()
                    continue
                if subdata.status == 301:
                    _outcome = poco.subscribe.update_url(args, subdata)
                    if _outcome.success is True:
                        poco.output.plans_moved(subdata, _outcome)
                if subdata.status == 304:
                    skip_subs.append(subdata)
                    update_q.task_done()
                    poco.output.plans_nochanges(subdata)
                    continue
                poco.output.plans_upgrade(subdata)
                upgrade_thread = poco.subupgrade.SubUpgradeThread(
                    subdata, update_q, poco.subupgrade.SubUpgrade)
                upgrade_threads.append(upgrade_thread)
                upgrade_thread.start()
            sleep(0.5)
        for upgrade_thread in upgrade_threads:
            upgrade_thread.join()

        # wrap up
        poco.output.after_stream_flush()
        poco.output.email_summary()

    except KeyboardInterrupt:
        for thread in upgrade_threads:
            setattr(thread, "kill", True)
        sys.exit()

if __name__ == '__main__':
    main()
