#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright 2010-2017 Mads Michelsen (mail@brokkr.net)
# This file is part of Poca.
# Poca is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.

"""A subscription management tool for poca"""


import poco

def main():
    '''Main script'''
    args = poco.args.get_poca_subscribe_args()
    stream_logger = poco.loggers.start_streamlogger(args)
    config = poco.config.Config(args)


def search(root, search_term):
    search_str = './subscriptions/subscription[contains(title, "%s")]' % searchterm
    results = root.xpath(search_str)
    return results

def delete(root, search_term):
    results = search(root, search_term)
    for result in results:
        root.subscriptions.remove(result)
    root_str = etree.tostring(root, pretty_print=True, xml_declaration=True)
    with open('/tmp/test.xml') as f:
        f.write(root_str)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
