#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright 2010-2017 Mads Michelsen (mail@brokkr.net)
# This file is part of Poca.
# Poca is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.

"""A cron-friendly command line podcast aggregator"""


from queue import Queue
import poco
from threading import Thread
from random import randint
from time import sleep


def main():
    '''Main script'''
    # setup
    args = poco.args.get_poca_args()
    stream_logger = poco.loggers.start_streamlogger(args)
    conf = poco.config.Config(args, merge_default=True)
    summary_logger = poco.loggers.start_summarylogger(args, conf.paths,
                                                      conf.xml.settings)

    # update loop
    update_threads = []
    update_q = Queue()
    xp_str = './subscription[not(@state="inactive")][title][url]'
    valid_subs = conf.xml.subscriptions.xpath(xp_str)
    for sub in valid_subs:
        thread = poco.subupdate.SubThread(update_q, poco.subupdate.SubData, conf, sub)
        update_threads.append(thread)
        thread.start()
    for thread in update_threads:
        thread.join()
    upgrade_threads = []
    upgrade_q = Queue()
    while upgrade_q.qsize() < len(valid_subs):
        while upgrade_q.unfinished_tasks < 4 and not update_q.empty():
            t = None
            upgrade_threads.append(t)
            t.start()

    #update_lst = []
    #while not update_q.empty():
    #    update_lst.append(update_q.get())
    #print(update_lst)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass


    #if summary_logger.poca_email_handler:
    #    summary_logger.poca_email_handler.close()
    #    outcome = summary_logger.poca_email_handler.outcome
    #    if outcome.success is False:
    #        poco.output.conffatal('Email log failed with: ')
    #        poco.output.conffatal('  ' + outcome.msg)
class TestThread(Thread):
    def __init__(self, q, subdata):
        self.subdata = subdata
        self.q = q
        super(TestThread, self).__init__()

    def run(self):
        sleep(randint(1, 10))
        print(self.name, self.subdata.sub.title)
        self.q.task_done()
